### PR TITLE
to add video files and docusaurus changes

### PR DESCRIPTION
**Pull request by bumblefudge**
Added video as an example page.  Not too much text, but check that I didn't say anything wrong or unhelpful about how to replace Richard Hopper with other text, which was definitely my (and Jefferson's) first question!

### CODE REVIEW

**Comment by clehner** [comment]
Video looks good to me, but adding a large file (26M) makes the repo slower/heavier to work with. Could the media be stored somewhere else?

Also I wonder if a video format like `mp4` could be better for user bandwidth - allowing the browser to load it more incrementally.

**Comment by wyc** [comment]
Agreed with smaller file sizes, but I don't think GH allows mp4s displayed in the README.

This author seems to have gotten theirs down to 4 MB:
https://dev.to/kelli/demo-your-app-in-your-github-readme-with-an-animated-gif-2o3c

**Comment by bumblefudge** [comment]
image
Turns out this S>G freeware makes editing the delays super easy in an animated GIF.  Good to know!

**Comment by bumblefudge** [comment]
Sadly, laboriously deleting all redundant stills and tweaking delays only got us down to 12MB.

**Comment by clehner** [comment]
@bumblefudge That's a good improvement.
It would still be nice to not have large binaries in the git repo.
If it could be under 10MB, it could be added to GitHub as an attachment: attach or drag-and-drop the file into a issue/PR/comment and grab the resulting markdown.

[gifsicle](http://www.lcdf.org/gifsicle/) is useful for manipulating GIFs. Here is a command to reduce the dimensions of the image by half (from `1080x1920` to `540x960`):
```
gifsicle credible-vc-vp.gif --scale 0.5 -o credible-vc-vp-half.gif
```
The resulting file is 6.3M. Markdown:
```
![credible-vc-vp-half](https://user-images.githubusercontent.com/95347/113591505-f422ff00-9601-11eb-9e16-4d0c45ab8ef9.gif)
```
Result:
credible-vc-vp-half

If using this, I recommend amending or re-committing your commit to this PR to remove the large file and then force-pushing to the PR branch. Or open a new PR with it and delete this one's branch.

**Pull request closed without merging**
