### PR TITLE
Create landing page for spruceid.dev with quick intro to DIDkit

### PR DESCRIPTION
**Pull request by mariavillosa**
There are two ways we can go about this:

1. Redirect spruceid.dev to a splash with a lightning intro to DIDKit et al, with links to other docs. This is what I'm demonstrating here in this draft right now. Or,
2.  Host the lightning introduction right there at spruceid.dev with no redirect. If we do it this way, I believe we'll have to make the page in React instead of Markdown.

I tried it both ways and it was easy either way. For reference, here are screenshots of how they look with some mock content:

## With markdown:

Screenshot from 2021-09-10 15-24-43

## With React

Screenshot from 2021-09-10 15-26-14

---

I'm equally comfortable in React and Markdown, so it's mostly a matter of which is more important: the convenience of markdown versus the clean URL goodness of doing it directly in React. Not a huge deal either way.

Draft for now since this is just giving an idea of different approaches.

### CODE REVIEW

**Comment by bumblefudge** [comment]
Oooohh, React way for sure!

**Comment by mariavillosa** [comment]
Okay, I've changed it to React. Please let me know if you have any questions, or if there's anything in particular you'd like to be able to do easily so I can put an example for you to copy/paste :)

Since it's React, we can pretty much do anything. I included a mini-Pokedex app, for example. Probably we won't need that much custom programming type stuff but it's there in case you want to do anything eccentric.

Here is a screenshot of how it renders:

screencapture-localhost-3000-2021-09-11-20_23_02

Just let me know what else you need!

**Review by bumblefudge — APPROVED** [review]

**Comment by mariavillosa** [comment]
Added an example dropdown of links. Also added feature to code blocks so bash code will start with `$` which won't be copied (other languages will not have this)

**Comment by mariavillosa** [comment]
Here's how things look now:

Screenshot from 2021-09-12 15-14-39

**Comment by mariavillosa** [comment]
This is no good:

Screenshot from 2021-09-12 16-51-23

`$` should only appear on lines representing a terminal prompt. The other lines (that are multiline quoted) would be represented differently, for example on some terminals they start with `>`, or nothing at all. In any case, what we're doing now is wrong and looks awkward in situations like this, where certain lines don't represent a new prompt.

Solutions:

1. Just let it be (it's not the end of the world, but it *does* look kinda bad)
2. Remove the `$`'s altogether (easy, simple path)
3. Only apply the $'s to snippets that are all one-liners

Let me know which solution is preferred and I'll make it happen.

**Comment by bumblefudge** [comment]
I think 3 is possible if we just reserve ` ```bash` for snippets that are all one-liners and make cases like these unformatted ` ``` `

**Pull request merged**
